# version: 2.1
# jobs:
#   build:
#     working_directory: ~/public
#     docker:
#       - image: circleci/node:16.13.1
#     steps:
#       - checkout
#       - run:
#           name: update-npm
#           command: "sudo npm install -g npm@latest"
#     #   - restore_cache:
#     #       key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: install-npm-wee
#           command: npm install
#     #   - save_cache:
#     #       key: dependency-cache-{{ checksum "package.json" }}
#     #       paths:
#     #         - ./node_modules
#       - run:
#           name: test
#           command: npm test --forceExit
#           no_output_timeout: 1200


#     parallelism: 4

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:16.13.1

    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test


    parallelism: 4
